SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CHCN_LCRDATA_LIMITEDDATA_MATCHED_TO_CAPDATA_SP]
AS
BEGIN
SELECT      LCR.*, dbo.CHCN_837_ORIGDATA_LIMITED_VS.ORIG_PROV_ID,EA_02_MedRecNO
FROM           DBO.Members_Cap_Period_Within_Claim_DOS_LCR AS LCR left JOIN
                         dbo.CHCN_837_ORIGDATA_LIMITED_VS ON 
                       LCR.CLAIMNO = dbo.CHCN_837_ORIGDATA_LIMITED_VS.EZCAP_CLAIMNO
					 
						 END
GO
