IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CHCN-EB\TABLEAU2')
CREATE LOGIN [CHCN-EB\TABLEAU2] FROM WINDOWS
GO
CREATE USER [CHCN-EB\TABLEAU2] FOR LOGIN [CHCN-EB\TABLEAU2]
GO
