IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CHCN-EB\CGOVINDU')
CREATE LOGIN [CHCN-EB\CGOVINDU] FROM WINDOWS
GO
CREATE USER [CHCN-EB\CGOVINDU] FOR LOGIN [CHCN-EB\CGOVINDU]
GO
